Used hamcrest matcher "notNullValue"
HusseinElFeky/movies-explorer pull request #1
Opened 2022-11-08 08:50 UTC by meaem

Using the **notNullValue** hamcrest matcher in the test is more preferable than using **isNullOrEmpty** to check the list content

2022-11-11 23:00 UTC, hfeky requested changes
Thank you for considering to contribute, @meaem! Please check my comments below, then we can merge it. :)

2022-11-11 23:00 UTC, hfeky commented on app/src/test/java/com/husseinelfeky/moviesexplorer/master/MasterViewModelTest.kt
> +        assertThat(result.size, `is`(0))
This would cause the test to fail, but we can change it to the following, since the result can never be null.

```suggestion
        assertThat(result.isEmpty(), `is`(false))
```

2022-11-11 23:00 UTC, hfeky commented on app/src/test/java/com/husseinelfeky/moviesexplorer/master/MasterViewModelTest.kt
>          assertThat(result.size, `is`(8))
It would actually be better to remove this assertion completely, since the result can never be null and we already assert the list size right below.

```suggestion
        assertThat(result.size, `is`(8))
```

2022-11-11 23:00 UTC, hfeky commented on app/src/test/java/com/husseinelfeky/moviesexplorer/master/MasterViewModelTest.kt
> +import org.hamcrest.CoreMatchers.notNullValue
This import would not be needed anymore now.

```suggestion
```

2022-11-15 09:59 UTC, meaem commented on app/src/test/java/com/husseinelfeky/moviesexplorer/master/MasterViewModelTest.kt
>          assertThat(result.size, `is`(8))
Yes you are right

2022-11-15 10:01 UTC, meaem commented on app/src/test/java/com/husseinelfeky/moviesexplorer/master/MasterViewModelTest.kt
> +import org.hamcrest.CoreMatchers.notNullValue
yes of course

2022-11-15 10:01 UTC, meaem commented
This issue has been resolved

2022-11-15 10:01 UTC, closed without merging